### ISSUE TITLE
Unable to get emulate to connect

### ISSUE THREAD

**Issue by jlandwerlen** [jlbcontrols/Flintium#178]
Following this guide, https://github.com/jlbcontrols/Flintium/wiki/Setting-up-RSLogix-Emulate, I was unable to connect.  Using v32 emulate within Win7x64 VM, v8.0.10 Ignition, Logix driver +21.  Perhaps there is a step or two missing?

**Comment by jlbcontrols** [comment]
@tord-v I know you had some trouble getting this to work as well. Were you able to get it working? Any tips or tricks needed?

It worked without any problems for me. Emulate v32, Windows 10 VM, Ignition v8.0.12 (also on v8.0.6). I'll add more screenshots to the Wiki.

**Comment by jlbcontrols** [comment]
Connecting Ignition to Emulate does not work when using Windows 7. Its not clear why, but the procedure described in the Wiki only works for Windows 10.
[Setting up RSLogix Emulate](https://github.com/jlbcontrols/Flintium/wiki/Setting-up-RSLogix-Emulate)
